# Generated by Django 5.0.7 on 2024-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
