# Generated by Django 5.0.7 on 2024-08-31 09:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='ibhuo9ahkqa8kxbg211l', max_length=255, verbose_name='avatar'),
        ),
    ]
