# Generated by Django 5.0.7 on 2024-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
