# Generated by Django 5.0.7 on 2024-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='desc',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='district',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='healthCard',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
