# Generated by Django 5.0.7 on 2024-08-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepagedb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
