# Generated by Django 5.0.7 on 2024-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
