# Generated by Django 5.0.7 on 2024-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofile_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='fees',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_district',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_state',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2, null=True),
        ),
    ]
