# Generated by Django 5.0.7 on 2024-08-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofile_fees_doctorprofile_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='ratings',
        ),
    ]
