# Generated by Django 5.0.7 on 2024-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctorprofile_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='desc',
            field=models.TextField(default='Your Bio goes here', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='fees',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital',
            field=models.CharField(default='--', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_district',
            field=models.CharField(default='--', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_state',
            field=models.CharField(default='--', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='reg_no',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialist',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
