# Generated by Django 5.0.7 on 2024-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctorprofile_degree_alter_doctorprofile_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='fees',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital',
            field=models.CharField(default='--', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_district',
            field=models.CharField(default='--', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_state',
            field=models.CharField(default='--', max_length=150),
        ),
    ]
