# Generated by Django 5.0.7 on 2024-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctorprofile_degree_alter_doctorprofile_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='avail',
            field=models.BooleanField(default=False),
        ),
    ]
