# Generated by Django 5.0.7 on 2024-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctorprofile_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='upi_id',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
