# Generated by Django 5.0.7 on 2024-09-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctorprofile_upi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='upi_id',
        ),
    ]
