# Generated by Django 5.0.7 on 2024-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_doctorprofile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='upi_id',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
