# Generated by Django 5.0.7 on 2024-09-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0014_doctorprofile_room_id'),
        ('patient', '0002_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(max_length=200)),
                ('prescription', models.TextField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Under Treatment'), (2, 'Checkup Done')], default=0, max_length=15)),
                ('doctor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
        ),
    ]
