# Generated by Django 5.0.7 on 2024-09-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Under Treatment'), (2, 'Checkup Done')], default=0),
        ),
    ]
