# Generated by Django 5.0.7 on 2024-09-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('doctor', '0014_doctorprofile_room_id'),
        ('patient', '0002_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doctor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prescription',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
