# Generated by Django 5.0.7 on 2024-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pr_no',
            field=models.CharField(default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='presribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prescription',
            field=models.TextField(default='--', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.TextField(default='--', max_length=200, null=True),
        ),
    ]
