# Generated by Django 5.0.7 on 2024-09-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_pr_no_booking_presribed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='presribed_date',
            new_name='prescribed_date',
        ),
    ]
