# Generated by Django 5.0.7 on 2024-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_presribed_date_booking_prescribed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pr_no',
            field=models.CharField(default='--', max_length=40),
        ),
    ]
